export const tokensProduct = [
  {
    id: 0,
    name: 'Common Sense Index',
    symbol: 'CSI',
    image: 'https://static.commonsense.finance/csi-token.svg',
    fee: '2%',
    contractPolygon: '0x1fd078168fad608910687b1385d7cf0d31ac64b4',
    contract: '',
    decimals: '18',
    price: 0,
    balance: 0,
    total: 0,
    allowance: 0,
    about:
      "The Common Sense Index Token (CSI) aims to replicate the profitability of an index composed of the Top 8 cryptocurrencies in the Polygon Network (ERC20) with a market capitalization of over 2 billion. The weight of each asset is limited to 25% and the weight of each category is limited to 50%. Rebalancing is done quarterly.",
    marketCap: 0,
    totalSupply: 0,
    components: [],
  },
  // {
  //   id: 1,
  //   name: 'CS Top10 Index',
  //   symbol: 'CSTOP',
  //   image: '/icons/cstop.svg',
  //   fee: '2%',
  //   contractPolygon: '0xff3ee79CB4A7Fe0F78a3634cCfDbFc3CdCD65a64',
  //   contract: '',
  //   decimals: '18',
  //   price: 0,
  //   balance: 0,
  //   total: 0,
  //   allowance: 0,
  //   about:
  //     "The CSTOP 'All in One' Token aims to replicate the profitability of an index composed of the Top 10 cryptocurrencies in the Ethereum Network (ERC20) with a market capitalization of over 1 billion. The weight of each asset is limited to 25% and the weight of each category is limited to 50%. Rebalancing is done quarterly.",
  //   marketCap: 0,
  //   totalSupply: 0,
  //   components: [],
  // },
  // {
  //   id: 2,
  //   name: 'Tmatic & Teth',
  //   symbol: 'TST',
  //   image: '',
  //   fee: '0%',
  //   contractPolygon: '0x04A250E193571A5621998F61bb258701c8a6034d',
  //   contract: '',
  //   decimals: '18',
  //   price: 0,
  //   balance: 0,
  //   total: 0,
  //   allowance: 0,
  //   about:
  //     "The TST 'All in One' Token aims to replicate the profitability of an index composed of the Top 10 cryptocurrencies in the Ethereum Network (ERC20) with a market capitalization of over 1 billion. The weight of each asset is limited to 25% and the weight of each category is limited to 50%. Rebalancing is done quarterly.",
  //   marketCap: 0,
  //   totalSupply: 0,
  //   components: [],
  // },
]

// export const ComponentsTokenProduct = [
//   [
//     {
//       id: 0,
//       symbol: 'WBTC',
//       image: 'https://assets.coingecko.com/coins/images/7598/small/wrapped_bitcoin_wbtc.png',
//       decimals: 8,
//       position: '25%',
//       price: 0,
//       contractPolygon: '',
//     },
//     {
//       id: 1,
//       symbol: 'WETH',
//       image: 'https://assets.coingecko.com/coins/images/2518/small/weth.png',
//       decimals: 18,
//       position: '25%',
//       price: 0,
//       contractPolygon: '',
//     },
//     {
//       id: 2,
//       symbol: 'LINK',
//       image: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png',
//       decimals: 18,
//       position: '14%',
//       price: 0,
//       contractPolygon: '',
//     },
//     {
//       id: 3,
//       symbol: 'WMATIC',
//       image: 'https://assets.coingecko.com/coins/images/14073/small/matic.png',
//       decimals: 18,
//       position: '13%',
//       price: 0,
//       contractPolygon: '',
//     },
//     {
//       id: 4,
//       symbol: 'UNI',
//       image: 'https://assets.coingecko.com/coins/images/12504/small/uniswap-uni.png',
//       decimals: 18,
//       position: '13%',
//       price: 0,
//       contractPolygon: '',
//     },
//     {
//       id: 5,
//       symbol: 'AAVE',
//       image: 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png',
//       decimals: 18,
//       position: '5%',
//       price: 0,
//       contractPolygon: '',
//     },
//     {
//       id: 6,
//       symbol: 'SUSHI',
//       image: 'https://assets.coingecko.com/coins/images/12271/small/512x512_Logo_no_chop.png',
//       decimals: 18,
//       position: '3%',
//       price: 0,
//       contractPolygon: '',
//     },
//     {
//       id: 7,
//       symbol: 'TEL',
//       image: 'https://assets.coingecko.com/coins/images/1899/small/tel.png',
//       decimals: 18,
//       position: '2%',
//       price: 0,
//       contractPolygon: '',
//     }
//   ]
// ]

// export enum tokensImage {
//   WBTC = 'WBTC',
//   WETH = 'ETH',
//   LINK = 'LINK',
// }

export enum tokensImage {
  WBTC = 'https://assets.coingecko.com/coins/images/7598/small/wrapped_bitcoin_wbtc.png',
  WETH = 'https://assets.coingecko.com/coins/images/2518/small/weth.png',
  LINK = 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png',
  WMATIC = 'https://assets.coingecko.com/coins/images/14073/small/matic.png',
  UNI = 'https://assets.coingecko.com/coins/images/12504/small/uniswap-uni.png',
  AAVE = 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png',
  SUSHI = 'https://assets.coingecko.com/coins/images/12271/small/512x512_Logo_no_chop.png',
  TEL = 'https://assets.coingecko.com/coins/images/1899/small/tel.png',
  DAI = 'https://assets.coingecko.com/coins/images/9956/small/4943.png',
  USDT = 'https://assets.coingecko.com/coins/images/325/small/Tether-logo.png',
  USDC = 'https://assets.coingecko.com/coins/images/6319/small/USD_Coin_icon.png',
  MATIC = 'https://assets.coingecko.com/coins/images/4713/small/matic-token-icon.png'

}

export const tokens = [
  {
    id: 0,
    symbol: 'WETH',
    name: 'Wrapped Ether',
    image: 'https://assets.coingecko.com/coins/images/2518/small/weth.png',
    fee: '0%',
    contractPolygon: '0x7ceb23fd6bc0add59e62ac25578270cff1b9f619',
    contract: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
    decimals: '18',
    price: 0,
    balance: 0,
    total: 0,
    allowance: 0,
    about: '',
    marketCap: 0,
    totalSupply: 0,
    components: [],
  },
  {
    id: 1,
    symbol: 'WBTC',
    name: 'Wrapped BTC',
    image: 'https://assets.coingecko.com/coins/images/7598/small/wrapped_bitcoin_wbtc.png',
    fee: '0%',
    contractPolygon: '0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6',
    contract: '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599',
    decimals: '8',
    price: 0,
    balance: 0,
    total: 0,
    allowance: 0,
    about: '',
    marketCap: 0,
    totalSupply: 0,
    components: [],
  },
  {
    id: 2,
    symbol: 'DAI',
    name: 'Dai Stablecoin',
    image: '',
    fee: '0%',
    contractPolygon: '0x8f3cf7ad23cd3cadbd9735aff958023239c6a063',
    contract: '0x6b175474e89094c44da98b954eedeac495271d0f',
    decimals: '18',
    price: 0,
    balance: 0,
    total: 0,
    allowance: 0,
    about: '',
    marketCap: 0,
    totalSupply: 0,
    components: [],
  },
  {
    id: 3,
    symbol: 'WMATIC',
    name: 'Wrapped Matic',
    image: 'https://assets.coingecko.com/coins/images/14073/small/matic.png',
    fee: '0%',
    contractPolygon: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270',
    contract: '0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0',
    decimals: '18',
    price: 0,
    balance: 0,
    total: 0,
    allowance: 0,
    about: '',
    marketCap: 0,
    totalSupply: 0,
    components: [],
  },
  {
    id: 4,
    symbol: 'USDT',
    name: 'Tether USD',
    image: '',
    fee: '0%',
    contractPolygon: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f',
    contract: '0xdac17f958d2ee523a2206206994597c13d831ec7',
    decimals: '6',
    price: 0,
    balance: 0,
    total: 0,
    allowance: 0,
    about: '',
    marketCap: 0,
    totalSupply: 0,
    components: [],
  },
  {
    id: 5,
    symbol: 'USDC',
    name: 'USD Coin',
    image: '',
    fee: '0%',
    contractPolygon: '0x2791bca1f2de4661ed88a30c99a7a9449aa84174',
    contract: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    decimals: '6',
    price: 0,
    balance: 0,
    total: 0,
    allowance: 0,
    about: '',
    marketCap: 0,
    totalSupply: 0,
    components: [],
  },
]

export const DAI = tokens[2]

